### ISSUE TITLE
右键菜单位置的BUG

### ISSUE THREAD

**Issue by ying911008** [TinyWisp/vue-tree#1]
反馈一个右键菜单的bug，当鼠标位置在tree的边界时，右键菜单内容会被遮住，是否考虑临界值的时候自动调节菜单位置
![QQ图片20210813110817](https://user-images.githubusercontent.com/9350416/129300049-0865170d-0350-446b-9b39-26967cc0268f.png)

**Comment by TinyWisp** [comment]
正常情况下，是会显示出来的, 即使容器带有overflow: hidden，也是会显示出来的。

我猜测你那儿是用了一个菜单组件，你可以先试试不使用组件，只用一个简单的div试试。
一个简单的右键菜单是这样的
```vue
<template v-slot:contextmenu="{node}">
  <div class="menu">
  </div>
</template>
```
```css
.menu {
  width: 10em;
  height: 5em;
  border: 1px solid red;
  background-color: green;
}
```
看下菜单是否能完全展示出来。
